### ISSUE TITLE
Face tracklet 출력 변경

### ISSUE THREAD

**Issue by kyukyukyu** [kyukyukyu/ugproj-detector#30]
## TODO
- [x] 설정 파일에 face tracklet 관련 옵션 추가
  - [x] 각 face의 크기 (e.g. 값이 64로 들어오면 각 face의 크기는 64x64.)
  - [x] Row 당 column의 수
- [x] 설정에 따라 face tracklet 출력하기
  - [x] Frame position을 이미지에 기록하는 코드 지우기
  - [x] Frame position을 face tracklet metadata 파일에 기록하기
## 설정 파일에 옵션 추가

이런 식으로 설정 파일을 작성하도록 정하여 face tracker와 face clusterer 모두에서 이 옵션들을 사용할 수 있도록 하고자 한다.

``` cfg
[tracklet]
face_size = 64
n_cols = 16
```
## Face tracklet 출력

현재는 face tracker에서 단순 visualization 목적으로 출력하고 있는 face tracklet 이미지를 앞으로는 face clusterer의 입력 데이터로 사용하고자 한다. 그래서 face가 등장한 frame position을 face tracklet 이미지에 기록하는 대신에, face tracklet metadata를 담는 파일을 작성하여 여기에 기록하고자 한다.

Face tracklet metadata 파일에는 face tracklet 이미지에 기록된 각 face가 등장한 frame position이 순서대로 기록될 것이다. Face tracklet metadata 파일 형식으로는 YAML이 적합해 보인다. 이슈 #18 에서 [jbeder/yaml-cpp](https://github.com/jbeder/yaml-cpp)를 사용하여 YAML parsing 하는 것을 제안한 적이 있었는데, 찾아보니 [OpenCV에서 이미 YAML persistance를 지원하고 있었다.](http://docs.opencv.org/modules/core/doc/xml_yaml_persistence.html) 그래서 그냥 이거 쓰면 될 거 같다. 출력은 다음과 같이 되도록.

``` yaml
%YAML:1.0
frame_positions: [295, 298, 300, 303, 305, 307]
```

Face tracklet 이미지 파일과 metadata 파일의 이름은 각각 `tracklet_4.png`, `tracklet_4.yaml`과 같은 형태를 띠도록 한다. 이미지 파일의 이름이 지금 `face_4.png`와 같은 형태를 띠고 있는데, 이는 (헷갈리게도) tracklet을 나타내는 클래스가 `ugproj::Face` 라서 그렇다. 이슈 하나 새로 만들어서 terminology에 대해 정리할 필요가 있다.

**Comment by kyukyukyu** [comment]
Face tracklet이나 그 안에 들어가는 face를 표현하기 위해서 이미 만들어둔 클래스를 재활용하고 싶은데, face tracklet metadata에 frame position을 담으면 재활용할 수 없어진다. Face를 표현하는 클래스에서 얼굴의 등장 위치를 frame index로 표현하고 있기 때문이다.

그래서 face tracklet metadata에는 frame index를 담고, frame index와 frame position 사이의 mapping을 별도의 파일에 저장하는 것을 제안한다. 즉, [`src/main.cc`의 `tracked_positions`](https://github.com/kyukyukyu/ugproj-detector/blob/1f93e873bf0782f9237645fc5c035fa9bb0442d5/src/main.cc#L37)를 파일에 저장하는 것을 의미한다. Face tracklet metadata 형식은 아래와 같이 수정되어야 할 것이다.

``` yaml
%YAML:1.0
frame_indices: [98, 99, 100, 101, 102, 103]
```

**Comment by kyukyukyu** [comment]
Frame index - Frame position mapping은 다음과 같은 형태로 저장하는 것을 제안한다.

``` yaml
%YAML:1.0
frame_positions: [0, 3, 5, 8, 10, 12, 15, 17, 20]
```

Frame index - Frame position 'mapping'을 저장하는 것이 의도이지만, frame index는 0부터 시작하여 1씩 증가하기 때문에 YAML로 기록할 때 [sequence 타입](http://yaml.org/spec/1.0/#id2564419)을 사용해도 무방하다.
